
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "${KAFKA_UI_PORT:-8090}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  historical-producer:
    build: ./data-processors/producer
    env_file: .env
    environment:
      - SYMBOLS=${SYMBOLS:-BTC/USDT}
      - BACKFILL_DAYS=${BACKFILL_DAYS:-7}

    command: python historical_producer.py
    depends_on:
      - kafka
    restart: "no"

  realtime-producer:
    build: ./data-processors/producer
    env_file: .env
    environment:
      - SYMBOLS=${SYMBOLS:-BTC/USDT}
      - REALTIME_DELAY_SECONDS=${REALTIME_DELAY_SECONDS:-1}
      - TOPIC_NAME=${OHLCV_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BROKER}
    command: python realtime_producer.py
    depends_on:
      - kafka
    restart: unless-stopped

  ws-realtime-producer:
    build: ./data-processors/producer
    env_file: .env
    environment:
      - SYMBOLS=${SYMBOLS:-BTCUSDT,ETHUSDT}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - MARKET_STREAM_TOPIC=${MARKET_STREAM_TOPIC}
    command: python ws_realtime_producer.py
    depends_on:
      - kafka
    restart: unless-stopped

  signals-consumer:
    build: ./data-processors/signals-consumer
    env_file: .env
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - OHLCV_TOPIC=${OHLCV_TOPIC}
      - MARKET_STREAM_TOPIC=${MARKET_STREAM_TOPIC}
      - SIGNALS_TOPIC=${TRADING_SIGNALS_TOPIC}

      - INDICATOR_WINDOW=${INDICATOR_WINDOW:-200}
    command: python consumer.py
    depends_on:
      - kafka
    restart: unless-stopped
  db-consumer:
    build: ./data-processors/db-consumer
    env_file: .env
    environment:
      - TOPIC_NAME=${OHLCV_TOPIC}
      - KAFKA_BROKER=${KAFKA_BROKER}
    depends_on:
      - kafka
    restart: unless-stopped

